<script setup>
import Horses from "../Horses/Horses.vue";
</script>
<template>
  <table class="result_table" border="9" > <!--horses componentsinden gelen sonuçlar ekrana yazıdırılır-->
    <tr>
      <th>Yarışın Sonucu</th>
    </tr>
    <tr>
      <th>1. </th>
    </tr>
    <tr>
      <th>2. </th>
    </tr>
    <tr>
      <th>3. </th>
    </tr>
    <tr>
      <th>4. </th>
    </tr>
    <tr>
      <th>5. </th>
    </tr>
    <tr>
      <th>6. </th>
    </tr>
    <tr>
      <th>7. </th>
    </tr>
    <tr>
      <th>8. </th>
    </tr>
    
  </table>
</template>
<style scoped>
.result_table{
  margin-top: 50px;
  margin-right: 50px;
  width: 280px;
  height: 100px;
  border: 3px solid olive;
  text-align: center;
}
</style>
